name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          npm install
      - run: |
          npm run test
      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm run deploy
